In [18]:
import pandas as pd
import re
!pip install emoji
import emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 5.8 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [37]:
df = pd.read_csv('train.csv')
print(df.head(3))

      id                                          Book_Name  \
0  19635                নেভার স্টপ লার্নিং (হার্ডকভার)
1  31528   রাসুলুল্লাহ (স) এর নামায (১ম ও ২য় খণ্ড একত্রে...
2   9235                  পোয়েটিক জাস্টিস (পেপারব্যাক)

                                   Writer_Name  \
0                                 আয়মান সাদিক
1   আল্লামা মুহাম্মদ নাসীরুদ্দীন আলবানী (রহঃ)
2                              আগাথা ক্রিস্টি

                                            Category  Rating  \
0                                  ছাত্রজীবন উন্নয়ন        5
1                                       সালাত/নামায        1
2   রহস্য, গোয়েন্দা, ভৌতিক, মিথ, থ্রিলার, ও অ্যাড...       5

                                              Review      Site sentiment  \
0  মোটিভেশনাল ভিডিও দেখা শুরু হয়েছে ভাইয়ার ভিডিও ...  Rokomari  positive
1  আসসালামু আলাইকুম।ভাইয়েরা, বইটা নিঃসন্দেহে অবশ্...  Rokomari  negative
2  আগাথা ক্রিস্টির বিখ্যাত ক্রাইম নোভেল  "দ্য মার...  Rokomari  positive

   label
0      2
1      0
2      2

In [38]:
# keeping only necessary columns
df = df[['Review','label']]

In [39]:
df.head(10)

                                              Review  label
0  মোটিভেশনাল ভিডিও দেখা শুরু হয়েছে ভাইয়ার ভিডিও ...      2
1  আসসালামু আলাইকুম।ভাইয়েরা, বইটা নিঃসন্দেহে অবশ্...      0
2  আগাথা ক্রিস্টির বিখ্যাত ক্রাইম নোভেল  "দ্য মার...      2
3                                          দুর্দান্ত      2
4  বইঃ মাগফিরাতের পথ ও পাথেয়\nলেখক : ইমাম ইবনু রজ...      2
5             এটি আরবি শেখার জন্য একটি দুর্দান্ত বই।      2
6  এটি কি বই না বিস্ময়?আশ্চর্য সব প্রদীপ। একেকটি ...      2
7  তিনি তার নিজের ব্যক্তিগত জীবনের সামান্য স্মৃতি...      2
8                                        অনেক ভাল বই      2
9  বইটা খুবই সুন্দর কিন্ত আমি পড়ব না। শুধু নিজে এ...      2

Drop rows with missing Review or label

In [40]:
df = df.dropna(subset=['Review', 'label'])
df.head(5)

                                              Review  label
0  মোটিভেশনাল ভিডিও দেখা শুরু হয়েছে ভাইয়ার ভিডিও ...      2
1  আসসালামু আলাইকুম।ভাইয়েরা, বইটা নিঃসন্দেহে অবশ্...      0
2  আগাথা ক্রিস্টির বিখ্যাত ক্রাইম নোভেল  "দ্য মার...      2
3                                          দুর্দান্ত      2
4  বইঃ মাগফিরাতের পথ ও পাথেয়\nলেখক : ইমাম ইবনু রজ...      2

Normalize **whitespace**

In [41]:
def clean_whitespace(text):
    text = text.strip()
    text = re.sub(r'\s+', ' ', text)
    return text

In [42]:
df['Review'] = df['Review'].apply(clean_whitespace)
df.head(5)

                                              Review  label
0  মোটিভেশনাল ভিডিও দেখা শুরু হয়েছে ভাইয়ার ভিডিও ...      2
1  আসসালামু আলাইকুম।ভাইয়েরা, বইটা নিঃসন্দেহে অবশ্...      0
2  আগাথা ক্রিস্টির বিখ্যাত ক্রাইম নোভেল "দ্য মার্...      2
3                                          দুর্দান্ত      2
4  বইঃ মাগফিরাতের পথ ও পাথেয় লেখক : ইমাম ইবনু রজব...      2

Remove unnecessary **symbols**
1. keep English, Bengali, digits, basic punctuation
2. remove quotes

In [45]:
def remove_extra_symbols(text):
  text = re.sub(r'["“”]+', '', text)
  return text

In [46]:
df['Review'] = df['Review'].apply(remove_extra_symbols)
df.head(5)

                                              Review  label
0  মোটিভেশনাল ভিডিও দেখা শুরু হয়েছে ভাইয়ার ভিডিও ...      2
1  আসসালামু আলাইকুম।ভাইয়েরা, বইটা নিঃসন্দেহে অবশ্...      0
2  আগাথা ক্রিস্টির বিখ্যাত ক্রাইম নোভেল দ্য মার্ড...      2
3                                          দুর্দান্ত      2
4  বইঃ মাগফিরাতের পথ ও পাথেয় লেখক : ইমাম ইবনু রজব...      2

Lowercase **English** text only

In [47]:
def english_lower(text):
  result = []
  for c in text:
    if c.isascii():
      result.append(c.lower())
    else:
      result.append(c)
  return ''.join(result)

In [48]:
df['Review'] = df['Review'].apply(english_lower)
df.head(5)

                                              Review  label
0  মোটিভেশনাল ভিডিও দেখা শুরু হয়েছে ভাইয়ার ভিডিও ...      2
1  আসসালামু আলাইকুম।ভাইয়েরা, বইটা নিঃসন্দেহে অবশ্...      0
2  আগাথা ক্রিস্টির বিখ্যাত ক্রাইম নোভেল দ্য মার্ড...      2
3                                          দুর্দান্ত      2
4  বইঃ মাগফিরাতের পথ ও পাথেয় লেখক : ইমাম ইবনু রজব...      2

Convert **emojis** to text

In [49]:
def remove_emoji(text):
  return emoji.demojize(text)

In [50]:
df['Review'] = df['Review'].apply(remove_emoji)
df.head(5)

                                              Review  label
0  মোটিভেশনাল ভিডিও দেখা শুরু হয়েছে ভাইয়ার ভিডিও ...      2
1  আসসালামু আলাইকুম।ভাইয়েরা, বইটা নিঃসন্দেহে অবশ্...      0
2  আগাথা ক্রিস্টির বিখ্যাত ক্রাইম নোভেল দ্য মার্ড...      2
3                                          দুর্দান্ত      2
4  বইঃ মাগফিরাতের পথ ও পাথেয় লেখক : ইমাম ইবনু রজব...      2